version: '3'

services:
  # Frontend Service
  frontend-service:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - backend-service
    networks:
      - app-network

  # Authentication Service
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo-service
    environment:
      - MONGO_URI=mongodb://mongo-service:27017/auth
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=1d
    networks:
      - app-network

  # Backend API Service
  backend-service:
    build: ./backend-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo-service
    environment:
      - MONGO_URI=mongodb://mongo-service:27017/backend
      - JWT_SECRET=your_jwt_secret
    networks:
      - app-network

  # MongoDB Service
  mongo-service:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: