apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth-service:latest
        imagePullPolicy: Never # For local Minikube use
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: auth-configmap
              key: MONGO_URI
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: auth-configmap
              key: JWT_EXPIRES_IN
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: auth-configmap
              key: PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20